# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171114_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
